#!/bin/sqsh
#
echo "JTMOS OPERATING SYSTEM HELP"
echo "==========================="
echo "Currently you may test JTMOS with following commands:"
echo "ls        Lists directory"
echo "cp        Copies files: cp * /bin (only this specified syntax works)"
echo "ps        Lists all running processes"
echo "rm        Remove files, note SPECIAL syntax: rm dirt [equals to UNIX cmd:] rm *dirt*"
echo "rf        Read floppy disk(not tested well enough yet!)"
echo "memconfig Tells some information about app. memory configuration"
echo "install   Install new utilities from Squirrel Disk Archive"
echo "mkfs      Formats a drive, e.g.: mkfs hda [or] mkfs floppy [or] mkfs ram"
echo "cat       Print contents of a file to screen"
echo "clear     Clears screen"
echo "top       Displays top CPU hog processes"
echo "ren       Rename a file, syntax: ren [old name] [new name]"
echo "mkdir     Make directory, syntax: mkdir [directory]"
echo "cd        Change directory(shell internal), syntax: cd [directory]"
echo "sqdsk     Squirrel disk extractor utility(same as install but works for also files"
echo ""
echo "You may use ALT+F1,F2,F3, and so on to switch between terminals."
echo "ALT+F1=user window, ALT+F2=debugger window, ALT+F3=process creator"
echo "ALT+F4=cache window, ALT+F5=internet window, ALT+F6=message window"

