#!/bin/bash
./makgen.pl picture picture
./makgen.pl otest otest
./makgen.pl nzip nzip+nzipMain
./makgen.pl cp cp
./makgen.pl rt rt
./makgen.pl ps ps
./makgen.pl rm rm
./makgen.pl mv mv
./makgen.pl cat cat
./makgen.pl rf rf 
./makgen.pl ls ls
./makgen.pl listen listen
./makgen.pl plasma plasma
./makgen.pl plasma2 plasma2
./makgen.pl top top
./makgen.pl sqsh sqsh
./makgen.pl winshell winshell
./makgen.pl vgaplasma vgaplasma
./makgen.pl ren ren 
./makgen.pl mkfs mkfs
./makgen.pl d642zip d642zip
./makgen.pl idler idler
./makgen.pl setup setup
./makgen.pl snake snake
./makgen.pl sound sound
./makgen.pl aud aud
./makgen.pl cwdtest cwdtest
./makgen.pl filer filer
./makgen.pl filetest filetest
./makgen.pl float_test float_test
./makgen.pl fpuhard fpuhard
./makgen.pl fputest fputest
./makgen.pl sscanf_test sscanf_test
./makgen.pl val val
./makgen.pl wintest wintest
./makgen.pl wintest2 wintest2
./makgen.pl wintest3 wintest3
./makgen.pl writing writing
./makgen.pl wtest wtest
./makgen.pl runner runner
./makgen.pl edit edit+editEditor
./makgen.pl hello hello
./makgen.pl memconfig memconfig
./makgen.pl rawplay rawplay
./makgen.pl printtest printtest
./makgen.pl net net
./makgen.pl keytest keytest
./makgen.pl malloctest malloctest
./makgen.pl taskbar taskbar
./makgen.pl lar lar
./makgen.pl clear clear
#./makgen.pl unz unz+sqa+sqaMain
./makgen.pl sqa sqa+sqaMain
./makgen.pl test test
