#
#
# plasma2
#
# AUTOMATICALLY GENERATED MAKEFILE
# GENERATED BY makgen.pl 1.0.2004
#
APPNAME=plasma2
JTMOSSTDLIBCLOC=../libc/stlibc.o
STDSRC=../lib/stdapp.src
8TO1=TO1
BIN2C=../tools/bin2c
CC=gcc
CFLAGS=-Wall -w -c -O -march=i486 -DCPU=i586 -I../include
AR=ar
AS=as
ASM=nasm
ASMFLAGS=-f elf
LD=ld
LDFLAGS=-oformat=binary -Map $(APPNAME).map -T$(STDSRC) -L../lib -lcjtmos -o $(APPNAME).bin

default: linkit

		
linkit: application
	@echo ---: Linking out binary: plasma2.bin 
	$(LD) $(JTMOSSTDLIBCLOC) plasma2.o  $(LDFLAGS)

application:
	
	$(CC) $(CFLAGS) plasma2.c

clean:
	rm -f plasma2.o 
	
	
