#ifndef __INCLUDED_HDCACHECONFIG_H__
#define __INCLUDED_HDCACHECONFIG_H__

// NUMBER OF CACHE ENTRIES
#define N_HD_CACHE      	10
// MAXIMUM SIZE OF HD CACHE
#define MAX_CACHE_SIZE_K	10000
//#define MAX_CACHE_SIZE_K	64

#endif




