#
# Makefile for all applications in this directory
#
# applist.txt is used by kernel to check out which
# kernels will be featured in the kernel image.
#
# Check out wdb.h and graos.h for preferences
#
default: makeapps

makeapps:
		rm -f *.o
		make -f graos.mak

clean:
		rm -f *.o
		rm -f *.bin

#

