//
#ifndef __INCLUDED_PROCESSPRIORITIES_H__

//
#define THREAD_PRIORITY_HIGHEST			2
#define THREAD_PRIORITY_ABOVE_NORMAL		4
#define THREAD_PRIORITY_NORMAL                  8
#define THREAD_PRIORITY_BELOW_NORMAL		16
#define THREAD_PRIORITY_LOWEST			250
#define THREAD_PRIORITY_TIME_CRITICAL		1
#define THREAD_PRIORITY_IDLE			100

#endif
