/* (c)Copyright 1997-1999 by Jari Tapio Tuominen, ABSOLUTLY NO WARRANTY!
   See file COPYING for more information! */
/////////////////////////////////////////////////////////////////////////////
// Keyboard definations file for Finnish keyboard.
//
//

#define JTMKNUM_ESC      0x0001
#define JTMKNUM_ESCAPE   JTMKNUM_ESC
#define JTMKNUM_CTRL     0x001d
#define JTMKNUM_CURUP    0x0048
#define JTMKNUM_CURDOWN  0x0050
#define JTMKNUM_CURRIGHT 0x004b
#define JTMKNUM_CURLEFT  0x004d
#define JTMKNUM_F12      0x0058
#define JTMKNUM_PLUS     0x004e
#define JTMKNUM_MINUS    0x004a
#define JTMKNUM_ENTER    0x001c
#define JTMKNUM_INSERT   0x0052
#define JTMKNUM_DELETE   0x0053

