/* (c)Copyright 1997-1999 by Jari Tapio Tuominen, ABSOLUTLY NO WARRANTY!
   See file COPYING for more information! */
/*
 * JTMOS linux support - header file
 *
 * (C)1998 by Jari Tapio Tuominen, all rights reserved.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <vga.h>
#include <jtt/jtmglvar.h>
#include <jtt/jtmconv.h>
#include <jtt/jtmfile.h>
#include <jtt/jtmlsup.h>
