/* (c)Copyright 1997-1999 by Jari Tapio Tuominen, ABSOLUTLY NO WARRANTY!
   See file COPYING for more information! */
//
//     JTMOS window registry handling functions library - JWR library
//     (C)1998 by Jari Tapio Tuominen, all rights reserved.
//
// Description:
//
//      This library controls Window registry structure.
//      (struct)JTMGLVAR.H/jtmwreg
//
//
//
//
//
//
void jtmwr_initialize(void)
{
 jtmwreg.amount=0;
}


