#!/usr/bin/perl
#
require "tools.pl";

#
main();

#
sub CheckDir
{
	my ($i,$i2,@lst,$str,$str2);

	#
	@lst = LoadList("find $_[0] -maxdepth 1 -type f -name '*.c'|");
	if($#lst<0) { return; }

	#
	for($i=0; $i<($#lst+1); $i++)
	{
		#
		$objects[$n_objects] =		$lst[$i];
		$objects[$n_objects] =~		s/\.c$/.o/;
		$objects[$n_objects++] =~	s/^.*\/(.+\.o)$/$1/;
	}

	#
	$str = $_[0];
	$str =~ s/^.*\/(.+)$/$1/;
	$sections = "$sections$str ";

	#
	$str = "$str: ";
	for($i=0; $i<($#lst+1); $i++)
	{
		$str = "$str$lst[$i] ";
	}
	$str = "$str\n";

	#
	for($i=0; $i<($#lst+1); $i++)
	{
		$str2 = $lst[$i];
		$str2 =~ s/\.c$/.o/;
		$str = "$str\t\$(CC) \$(CFLAGS) $lst[$i] -o $str2\n";
	}
	$str = "$str\n";

	#
	return $str;
}

#
sub main
{
	my ($i,$i2,@lst,$str,$str2);

	#
	$n_objects = 0;
	$complines = "";
	$sections = "";

	#
	print("# JTMOS KERNEL MAKEFILE\n");
	print("# This file is automatically generated.\n");

	#
	@settings = LoadList("settings.txt");
	for($i=0; $i<($#settings+1); $i++)
	{
		print "$settings[$i]\n";
	}
	print "\n";

	#
	@lst = LoadList("find . -type d|");

	#
	for($i=0; $i<($#lst+1); $i++)
	{
		if($lst[$i] eq ".") { goto skip; }
		if($lst[$i] eq "..") { goto skip; }
		if( ($str=CheckDir($lst[$i])) ne "" )
		{
			$complines = $complines . $str;
		}
skip:
	}

	#
	print "OBJECTS = ";
	for($i=0; $i<($#objects+1); $i++)
	{
		print "$objects[$i] ";
	}
	print "\n";
	print "\n";

	#
	print "all: $sections";
	print "\n";
	print "\n";

	#
	print $complines;

	#
}

